/**
 * Research Workspace Templates System
 * 
 * Manages folder structure templates and file templates for research projects.
 * Supports different research types with customizable folder structures.
 * 
 * @module workspace-templates
 * @version 1.0.0
 */

import { promises as fs } from 'fs';
import path from 'path';
import { logger } from './logger.js';
import type { ResearchType } from './workspace-config.js';

/**
 * Folder template definition
 */
export interface FolderTemplate {
  name: string;
  path: string;
  description: string;
  subfolders?: FolderTemplate[];
  files?: FileTemplate[];
}

/**
 * File template definition
 */
export interface FileTemplate {
  name: string;
  content: string;
  description: string;
}

/**
 * Get base folder structure for all research types
 */
export function getBaseFolderStructure(): FolderTemplate[] {
  return [
    {
      name: 'citations',
      path: 'citations',
      description: 'Reference management and citation tracking',
      subfolders: [
        {
          name: 'raw',
          path: 'citations/raw',
          description: 'Original search results from databases',
          subfolders: [],
        },
        {
          name: 'deduplicated',
          path: 'citations/deduplicated',
          description: 'Citations after deduplication',
          subfolders: [],
        },
        {
          name: 'included',
          path: 'citations/included',
          description: 'Final included studies',
          subfolders: [],
        },
        {
          name: 'excluded',
          path: 'citations/excluded',
          description: 'Excluded studies with reasons',
          subfolders: [],
        },
      ],
      files: [
        {
          name: 'bibliography.bib',
          content: '% BibTeX Bibliography\n% Auto-generated by MedResearch AI\n\n',
          description: 'BibTeX export for reference managers',
        },
      ],
    },
    {
      name: 'data',
      path: 'data',
      description: 'Extracted data and quality assessments',
      subfolders: [
        {
          name: 'extraction-forms',
          path: 'data/extraction-forms',
          description: 'Data extraction templates',
          subfolders: [],
        },
        {
          name: 'extracted-data',
          path: 'data/extracted-data',
          description: 'Completed data extractions',
          subfolders: [],
        },
        {
          name: 'quality-assessment',
          path: 'data/quality-assessment',
          description: 'Risk of bias and quality assessments',
          subfolders: [],
        },
      ],
    },
    {
      name: 'analysis',
      path: 'analysis',
      description: 'Statistical analysis and meta-analysis',
      subfolders: [
        {
          name: 'meta-analysis',
          path: 'analysis/meta-analysis',
          description: 'Meta-analysis results and models',
          subfolders: [],
        },
        {
          name: 'subgroup-analysis',
          path: 'analysis/subgroup-analysis',
          description: 'Subgroup and sensitivity analyses',
          subfolders: [],
        },
        {
          name: 'sensitivity-analysis',
          path: 'analysis/sensitivity-analysis',
          description: 'Sensitivity analyses',
          subfolders: [],
        },
      ],
    },
    {
      name: 'figures',
      path: 'figures',
      description: 'Generated visualizations and plots',
      subfolders: [
        {
          name: 'forest-plots',
          path: 'figures/forest-plots',
          description: 'Forest plots for meta-analysis',
          subfolders: [],
        },
        {
          name: 'funnel-plots',
          path: 'figures/funnel-plots',
          description: 'Funnel plots for publication bias',
          subfolders: [],
        },
        {
          name: 'prisma-diagram',
          path: 'figures/prisma-diagram',
          description: 'PRISMA flow diagrams',
          subfolders: [],
        },
        {
          name: 'other',
          path: 'figures/other',
          description: 'Other figures and visualizations',
          subfolders: [],
        },
      ],
    },
    {
      name: 'tables',
      path: 'tables',
      description: 'Generated tables',
      subfolders: [
        {
          name: 'characteristics',
          path: 'tables/characteristics',
          description: 'Study characteristics tables',
          subfolders: [],
        },
        {
          name: 'results',
          path: 'tables/results',
          description: 'Results summary tables',
          subfolders: [],
        },
        {
          name: 'quality',
          path: 'tables/quality',
          description: 'Quality assessment summary tables',
          subfolders: [],
        },
      ],
    },
    {
      name: 'documents',
      path: 'documents',
      description: 'Final outputs and manuscripts',
      subfolders: [
        {
          name: 'manuscript',
          path: 'documents/manuscript',
          description: 'Main manuscript drafts',
          subfolders: [],
        },
        {
          name: 'supplementary',
          path: 'documents/supplementary',
          description: 'Supplementary materials',
          subfolders: [],
        },
        {
          name: 'presentation',
          path: 'documents/presentation',
          description: 'PowerPoint presentations',
          subfolders: [],
        },
        {
          name: 'protocol',
          path: 'documents/protocol',
          description: 'Study protocol',
          subfolders: [],
        },
      ],
    },
    {
      name: 'exports',
      path: 'exports',
      description: 'Export formats for external tools',
      subfolders: [
        {
          name: 'word',
          path: 'exports/word',
          description: 'Microsoft Word exports',
          subfolders: [],
        },
        {
          name: 'pdf',
          path: 'exports/pdf',
          description: 'PDF exports',
          subfolders: [],
        },
        {
          name: 'html',
          path: 'exports/html',
          description: 'HTML reports',
          subfolders: [],
        },
        {
          name: 'revman',
          path: 'exports/revman',
          description: 'RevMan format exports',
          subfolders: [],
        },
        {
          name: 'covidence',
          path: 'exports/covidence',
          description: 'Covidence CSV exports',
          subfolders: [],
        },
        {
          name: 'distillersr',
          path: 'exports/distillersr',
          description: 'DistillerSR exports',
          subfolders: [],
        },
        {
          name: 'prospero',
          path: 'exports/prospero',
          description: 'PROSPERO registration exports',
          subfolders: [],
        },
        {
          name: 'snapshots',
          path: 'exports/snapshots',
          description: 'Milestone snapshots',
          subfolders: [],
        },
      ],
    },
    {
      name: 'logs',
      path: 'logs',
      description: 'Process logs and history',
      subfolders: [
        {
          name: 'search-logs',
          path: 'logs/search-logs',
          description: 'Search history and queries',
          subfolders: [],
        },
        {
          name: 'screening-logs',
          path: 'logs/screening-logs',
          description: 'Screening decisions and rationale',
          subfolders: [],
        },
        {
          name: 'analysis-logs',
          path: 'logs/analysis-logs',
          description: 'Analysis execution logs',
          subfolders: [],
        },
      ],
    },
  ];
}

/**
 * Get research type specific folders
 */
export function getResearchTypeSpecificFolders(researchType: ResearchType): FolderTemplate[] {
  const specificFolders: Record<ResearchType, FolderTemplate[]> = {
    intervention: [
      {
        name: 'intervention-details',
        path: 'intervention-details',
        description: 'Detailed intervention descriptions',
        subfolders: [],
      },
      {
        name: 'outcome-measures',
        path: 'outcome-measures',
        description: 'Outcome measure definitions and data',
        subfolders: [],
      },
    ],
    diagnostic: [
      {
        name: 'test-accuracy-data',
        path: 'test-accuracy-data',
        description: 'Diagnostic test accuracy data',
        subfolders: [],
      },
      {
        name: 'sensitivity-specificity',
        path: 'sensitivity-specificity',
        description: 'Sensitivity and specificity analyses',
        subfolders: [],
      },
    ],
    prognostic: [
      {
        name: 'prognostic-factors',
        path: 'prognostic-factors',
        description: 'Prognostic factor data',
        subfolders: [],
      },
      {
        name: 'risk-models',
        path: 'risk-models',
        description: 'Risk prediction models',
        subfolders: [],
      },
    ],
    qualitative: [
      {
        name: 'themes',
        path: 'themes',
        description: 'Thematic analysis results',
        subfolders: [],
      },
      {
        name: 'quotes',
        path: 'quotes',
        description: 'Supporting quotations',
        subfolders: [],
      },
      {
        name: 'synthesis',
        path: 'synthesis',
        description: 'Qualitative synthesis',
        subfolders: [],
      },
    ],
    'mixed-methods': [
      {
        name: 'quantitative-data',
        path: 'quantitative-data',
        description: 'Quantitative component data',
        subfolders: [],
      },
      {
        name: 'qualitative-data',
        path: 'qualitative-data',
        description: 'Qualitative component data',
        subfolders: [],
      },
      {
        name: 'integration',
        path: 'integration',
        description: 'Mixed methods integration',
        subfolders: [],
      },
    ],
    scoping: [
      {
        name: 'concept-mapping',
        path: 'concept-mapping',
        description: 'Concept mapping and charting',
        subfolders: [],
      },
      {
        name: 'charting',
        path: 'charting',
        description: 'Data charting results',
        subfolders: [],
      },
    ],
    'systematic-review': [],
    'meta-analysis': [
      {
        name: 'statistical-models',
        path: 'statistical-models',
        description: 'Statistical model specifications',
        subfolders: [],
      },
    ],
  };

  return specificFolders[researchType] || [];
}

/**
 * Get complete folder structure for a research type
 */
export function getCompleteFolderStructure(researchType: ResearchType): FolderTemplate[] {
  const baseFolders = getBaseFolderStructure();
  const specificFolders = getResearchTypeSpecificFolders(researchType);
  return [...baseFolders, ...specificFolders];
}

/**
 * Create folder structure recursively
 */
export async function createFolderStructure(
  basePath: string,
  folders: FolderTemplate[]
): Promise<void> {
  for (const folder of folders) {
    const folderPath = path.join(basePath, folder.path);
    
    try {
      await fs.mkdir(folderPath, { recursive: true });
      logger.info(`Created folder: ${folder.path}`);
      
      // Create files in this folder
      if (folder.files) {
        for (const file of folder.files) {
          const filePath = path.join(folderPath, file.name);
          await fs.writeFile(filePath, file.content, 'utf-8');
          logger.info(`Created file: ${path.join(folder.path, file.name)}`);
        }
      }
      
      // Create subfolders recursively
      if (folder.subfolders && folder.subfolders.length > 0) {
        await createFolderStructure(basePath, folder.subfolders);
      }
    } catch (error) {
      logger.error(`Failed to create folder ${folder.path}:`, error);
      throw error;
    }
  }
}

/**
 * Get README template
 */
export function getReadmeTemplate(projectName: string, researchType: ResearchType): string {
  return `# ${projectName}

## Research Type
${researchType.charAt(0).toUpperCase() + researchType.slice(1).replace(/-/g, ' ')}

## Project Overview
This is a systematic review project managed by MedResearch AI.

## Folder Structure

- **citations/** - Reference management and citation tracking
  - **raw/** - Original search results
  - **deduplicated/** - After deduplication
  - **included/** - Final included studies
  - **excluded/** - Excluded studies with reasons

- **data/** - Extracted data and quality assessments
  - **extraction-forms/** - Data extraction templates
  - **extracted-data/** - Completed extractions
  - **quality-assessment/** - Risk of bias assessments

- **analysis/** - Statistical analysis
  - **meta-analysis/** - Meta-analysis results
  - **subgroup-analysis/** - Subgroup analyses
  - **sensitivity-analysis/** - Sensitivity analyses

- **figures/** - Generated visualizations
  - **forest-plots/** - Forest plots
  - **funnel-plots/** - Publication bias plots
  - **prisma-diagram/** - PRISMA flow diagram
  - **other/** - Other figures

- **tables/** - Generated tables
  - **characteristics/** - Study characteristics
  - **results/** - Results tables
  - **quality/** - Quality assessment tables

- **documents/** - Final outputs
  - **manuscript/** - Main manuscript
  - **supplementary/** - Supplementary materials
  - **presentation/** - PowerPoint presentations
  - **protocol/** - Study protocol

- **exports/** - Export formats
  - **word/** - .docx exports
  - **pdf/** - PDF exports
  - **html/** - HTML reports
  - **revman/** - RevMan format
  - **covidence/** - Covidence CSV
  - **distillersr/** - DistillerSR format
  - **prospero/** - PROSPERO registration
  - **snapshots/** - Milestone snapshots

- **logs/** - Process logs
  - **search-logs/** - Search history
  - **screening-logs/** - Screening decisions
  - **analysis-logs/** - Analysis runs

## Getting Started

1. Review the project metadata in \`metadata.json\`
2. Check the progress dashboard: \`progress-dashboard.html\`
3. Follow the research protocol in \`documents/protocol/\`

## Progress Tracking

- View progress: Open \`progress-dashboard.html\` in a browser
- Check status: See \`progress.md\` for human-readable summary
- Machine data: \`progress.json\` for programmatic access

## Configuration

- Project-specific settings: \`project-config.json\`
- Global settings: \`../../research-config.json\`

## Generated by MedResearch AI
Version: 1.0.0
Created: ${new Date().toISOString()}
`;
}

/**
 * Get metadata template
 */
export function getMetadataTemplate(
  projectId: string,
  projectName: string,
  researchType: ResearchType,
  client?: { firstName: string; lastName: string }
): string {
  const metadata = {
    projectId,
    projectName,
    researchType,
    client: client || null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'active',
    phase: 'planning',
    researchQuestion: '',
    pico: {
      population: '',
      intervention: '',
      comparator: '',
      outcome: '',
    },
    databases: [],
    team: {
      leadResearcher: client ? `${client.firstName} ${client.lastName}` : '',
      coResearchers: [],
    },
    timeline: {
      plannedStart: new Date().toISOString().split('T')[0],
      plannedEnd: '',
      actualStart: new Date().toISOString().split('T')[0],
      actualEnd: '',
    },
    milestones: {
      protocolCompleted: false,
      searchCompleted: false,
      screeningCompleted: false,
      extractionCompleted: false,
      qualityAssessmentCompleted: false,
      analysisCompleted: false,
      manuscriptCompleted: false,
    },
    statistics: {
      totalCitations: 0,
      duplicatesRemoved: 0,
      titleAbstractScreened: 0,
      fullTextReviewed: 0,
      studiesIncluded: 0,
      studiesExcluded: 0,
      dataExtracted: 0,
      qualityAssessed: 0,
    },
  };

  return JSON.stringify(metadata, null, 2);
}

/**
 * Get progress template
 */
export function getProgressTemplate(): string {
  const progress = {
    lastUpdated: new Date().toISOString(),
    overallProgress: 0,
    phases: {
      planning: {
        status: 'in_progress',
        progress: 0,
        tasks: {
          researchQuestionDefined: false,
          picoFormulated: false,
          protocolDrafted: false,
          protocolRegistered: false,
        },
      },
      search: {
        status: 'not_started',
        progress: 0,
        tasks: {
          searchStrategyDeveloped: false,
          databasesSearched: false,
          resultsImported: false,
          duplicatesRemoved: false,
        },
      },
      screening: {
        status: 'not_started',
        progress: 0,
        tasks: {
          titleAbstractScreening: false,
          fullTextScreening: false,
          inclusionCriteriaApplied: false,
        },
      },
      extraction: {
        status: 'not_started',
        progress: 0,
        tasks: {
          extractionFormDeveloped: false,
          dataExtracted: false,
          extractionVerified: false,
        },
      },
      qualityAssessment: {
        status: 'not_started',
        progress: 0,
        tasks: {
          toolSelected: false,
          assessmentCompleted: false,
          consensusReached: false,
        },
      },
      analysis: {
        status: 'not_started',
        progress: 0,
        tasks: {
          metaAnalysisPerformed: false,
          subgroupAnalysis: false,
          sensitivityAnalysis: false,
          publicationBiasAssessed: false,
        },
      },
      writing: {
        status: 'not_started',
        progress: 0,
        tasks: {
          introductionWritten: false,
          methodsWritten: false,
          resultsWritten: false,
          discussionWritten: false,
          abstractWritten: false,
        },
      },
    },
  };

  return JSON.stringify(progress, null, 2);
}

/**
 * Get progress markdown template
 */
export function getProgressMarkdownTemplate(projectName: string): string {
  return `# ${projectName} - Progress Report

**Last Updated**: ${new Date().toISOString()}

## Overall Progress: 0%

---

## Phase Progress

### 📋 Planning (0%)
- [ ] Research question defined
- [ ] PICO formulated
- [ ] Protocol drafted
- [ ] Protocol registered

### 🔍 Search (0%)
- [ ] Search strategy developed
- [ ] Databases searched
- [ ] Results imported
- [ ] Duplicates removed

### 📊 Screening (0%)
- [ ] Title/abstract screening
- [ ] Full-text screening
- [ ] Inclusion criteria applied

### 📝 Data Extraction (0%)
- [ ] Extraction form developed
- [ ] Data extracted
- [ ] Extraction verified

### ⭐ Quality Assessment (0%)
- [ ] Assessment tool selected
- [ ] Assessment completed
- [ ] Consensus reached

### 📈 Analysis (0%)
- [ ] Meta-analysis performed
- [ ] Subgroup analysis
- [ ] Sensitivity analysis
- [ ] Publication bias assessed

### ✍️ Writing (0%)
- [ ] Introduction written
- [ ] Methods written
- [ ] Results written
- [ ] Discussion written
- [ ] Abstract written

---

## Statistics

- **Total Citations**: 0
- **Duplicates Removed**: 0
- **Title/Abstract Screened**: 0
- **Full-Text Reviewed**: 0
- **Studies Included**: 0
- **Studies Excluded**: 0
- **Data Extracted**: 0
- **Quality Assessed**: 0

---

*Generated by MedResearch AI*
`;
}

/**
 * Get HTML dashboard template
 */
export function getHtmlDashboardTemplate(projectName: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="refresh" content="300">
    <title>${projectName} - Dashboard</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            background: #f5f7fa;
            padding: 20px;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
        }
        
        header {
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            margin-bottom: 20px;
        }
        
        h1 {
            color: #2c3e50;
            margin-bottom: 10px;
        }
        
        .last-updated {
            color: #7f8c8d;
            font-size: 14px;
        }
        
        .progress-overview {
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            margin-bottom: 20px;
        }
        
        .progress-bar {
            width: 100%;
            height: 30px;
            background: #ecf0f1;
            border-radius: 15px;
            overflow: hidden;
            margin: 20px 0;
        }
        
        .progress-fill {
            height: 100%;
            background: linear-gradient(90deg, #3498db, #2ecc71);
            width: 0%;
            transition: width 0.3s ease;
        }
        
        .phases {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 20px;
            margin-top: 20px;
        }
        
        .phase-card {
            background: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        
        .phase-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 15px;
        }
        
        .phase-title {
            font-size: 18px;
            font-weight: 600;
            color: #2c3e50;
        }
        
        .phase-status {
            padding: 5px 10px;
            border-radius: 5px;
            font-size: 12px;
            font-weight: 600;
        }
        
        .status-not-started {
            background: #ecf0f1;
            color: #7f8c8d;
        }
        
        .status-in-progress {
            background: #fff3cd;
            color: #856404;
        }
        
        .status-completed {
            background: #d4edda;
            color: #155724;
        }
        
        .task-list {
            list-style: none;
        }
        
        .task-item {
            padding: 8px 0;
            color: #7f8c8d;
        }
        
        .task-item.completed {
            color: #2ecc71;
        }
        
        .task-item::before {
            content: '☐ ';
            margin-right: 8px;
        }
        
        .task-item.completed::before {
            content: '☑ ';
        }
        
        .stats {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
            margin-top: 20px;
        }
        
        .stat-card {
            background: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            text-align: center;
        }
        
        .stat-value {
            font-size: 32px;
            font-weight: 700;
            color: #3498db;
            margin-bottom: 5px;
        }
        
        .stat-label {
            color: #7f8c8d;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>${projectName}</h1>
            <p class="last-updated">Last Updated: ${new Date().toLocaleString()}</p>
        </header>
        
        <div class="progress-overview">
            <h2>Overall Progress</h2>
            <div class="progress-bar">
                <div class="progress-fill" style="width: 0%"></div>
            </div>
            <p style="text-align: center; color: #7f8c8d;">0% Complete</p>
        </div>
        
        <h2 style="margin: 30px 0 20px 0; color: #2c3e50;">Phase Progress</h2>
        <div class="phases">
            <div class="phase-card">
                <div class="phase-header">
                    <span class="phase-title">📋 Planning</span>
                    <span class="phase-status status-in-progress">In Progress</span>
                </div>
                <ul class="task-list">
                    <li class="task-item">Research question defined</li>
                    <li class="task-item">PICO formulated</li>
                    <li class="task-item">Protocol drafted</li>
                    <li class="task-item">Protocol registered</li>
                </ul>
            </div>
            
            <div class="phase-card">
                <div class="phase-header">
                    <span class="phase-title">🔍 Search</span>
                    <span class="phase-status status-not-started">Not Started</span>
                </div>
                <ul class="task-list">
                    <li class="task-item">Search strategy developed</li>
                    <li class="task-item">Databases searched</li>
                    <li class="task-item">Results imported</li>
                    <li class="task-item">Duplicates removed</li>
                </ul>
            </div>
            
            <div class="phase-card">
                <div class="phase-header">
                    <span class="phase-title">📊 Screening</span>
                    <span class="phase-status status-not-started">Not Started</span>
                </div>
                <ul class="task-list">
                    <li class="task-item">Title/abstract screening</li>
                    <li class="task-item">Full-text screening</li>
                    <li class="task-item">Inclusion criteria applied</li>
                </ul>
            </div>
            
            <div class="phase-card">
                <div class="phase-header">
                    <span class="phase-title">📝 Data Extraction</span>
                    <span class="phase-status status-not-started">Not Started</span>
                </div>
                <ul class="task-list">
                    <li class="task-item">Extraction form developed</li>
                    <li class="task-item">Data extracted</li>
                    <li class="task-item">Extraction verified</li>
                </ul>
            </div>
            
            <div class="phase-card">
                <div class="phase-header">
                    <span class="phase-title">⭐ Quality Assessment</span>
                    <span class="phase-status status-not-started">Not Started</span>
                </div>
                <ul class="task-list">
                    <li class="task-item">Assessment tool selected</li>
                    <li class="task-item">Assessment completed</li>
                    <li class="task-item">Consensus reached</li>
                </ul>
            </div>
            
            <div class="phase-card">
                <div class="phase-header">
                    <span class="phase-title">📈 Analysis</span>
                    <span class="phase-status status-not-started">Not Started</span>
                </div>
                <ul class="task-list">
                    <li class="task-item">Meta-analysis performed</li>
                    <li class="task-item">Subgroup analysis</li>
                    <li class="task-item">Sensitivity analysis</li>
                    <li class="task-item">Publication bias assessed</li>
                </ul>
            </div>
            
            <div class="phase-card">
                <div class="phase-header">
                    <span class="phase-title">✍️ Writing</span>
                    <span class="phase-status status-not-started">Not Started</span>
                </div>
                <ul class="task-list">
                    <li class="task-item">Introduction written</li>
                    <li class="task-item">Methods written</li>
                    <li class="task-item">Results written</li>
                    <li class="task-item">Discussion written</li>
                    <li class="task-item">Abstract written</li>
                </ul>
            </div>
        </div>
        
        <h2 style="margin: 30px 0 20px 0; color: #2c3e50;">Statistics</h2>
        <div class="stats">
            <div class="stat-card">
                <div class="stat-value">0</div>
                <div class="stat-label">Total Citations</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">0</div>
                <div class="stat-label">Duplicates Removed</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">0</div>
                <div class="stat-label">Screened</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">0</div>
                <div class="stat-label">Included</div>
            </div>
        </div>
    </div>
</body>
</html>
`;
}

/**
 * Template manager class
 */
export class TemplateManager {
  /**
   * Create complete project structure
   */
  async createProjectStructure(
    projectPath: string,
    projectName: string,
    researchType: ResearchType,
    client?: { firstName: string; lastName: string }
  ): Promise<void> {
    try {
      // Create base directory
      await fs.mkdir(projectPath, { recursive: true });
      
      // Get folder structure
      const folders = getCompleteFolderStructure(researchType);
      
      // Create folders
      await createFolderStructure(projectPath, folders);
      
      // Create root files
      const projectId = path.basename(projectPath).split('_')[0];
      
      // README.md
      await fs.writeFile(
        path.join(projectPath, 'README.md'),
        getReadmeTemplate(projectName, researchType),
        'utf-8'
      );
      
      // metadata.json
      await fs.writeFile(
        path.join(projectPath, 'metadata.json'),
        getMetadataTemplate(projectId, projectName, researchType, client),
        'utf-8'
      );
      
      // progress.json
      await fs.writeFile(
        path.join(projectPath, 'progress.json'),
        getProgressTemplate(),
        'utf-8'
      );
      
      // progress.md
      await fs.writeFile(
        path.join(projectPath, 'progress.md'),
        getProgressMarkdownTemplate(projectName),
        'utf-8'
      );
      
      // progress-dashboard.html
      await fs.writeFile(
        path.join(projectPath, 'progress-dashboard.html'),
        getHtmlDashboardTemplate(projectName),
        'utf-8'
      );
      
      logger.info(`Project structure created successfully: ${projectName}`);
    } catch (error) {
      logger.error('Failed to create project structure:', error);
      throw error;
    }
  }
}

/**
 * Export singleton instance
 */
export const templateManager = new TemplateManager();
